### ISSUE TITLE
Prompt me for connection timeout when I use this library

### ISSUE THREAD

**Issue by MuLanMax** [ribasco/async-gamequery-lib#151]
My Code
 public static void main(String[] args) {
        SteamWebApiClient client = new SteamWebApiClient("727D5975998DB3C733D465EDCE60E***");
        SteamUser steamUser = new SteamUser(client);
        steamUser.getPlayerBans(Long.valueOf("76561199015*******")).thenAccept(steamBanStatuses ->
                steamBanStatuses.forEach(steamBanStatus ->
                        log.info("Ban status for {} = {}, Economy Ban: {}",
                                steamBanStatus.getSteamIdAsLong(),
                                steamBanStatus.isVacBanned(),
                                steamBanStatus.getEconomyBan()))).join();
    }

exception message
xception in thread "main" java.util.concurrent.CompletionException: java.net.ConnectException: connection timed out: api.steampowered.com/95.100.74.248:443
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:636)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at org.asynchttpclient.netty.NettyResponseFuture.abort(NettyResponseFuture.java:273)
	at org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:181)
	at org.asynchttpclient.netty.channel.NettyChannelConnector$1.onFailure(NettyChannelConnector.java:108)
	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:28)
	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:262)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: com.ibasco.agql.core.exceptions.WebException: java.util.concurrent.CompletionException: java.net.ConnectException: connection timed out: api.steampowered.com/95.100.74.248:443
		at com.ibasco.agql.core.AbstractWebApiInterface.handleError(AbstractWebApiInterface.java:198)
		at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
		at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
		... 27 more
	Caused by: [CIRCULAR REFERENCE: java.util.concurrent.CompletionException: java.net.ConnectException: connection timed out: api.steampowered.com/95.100.74.248:443]
Caused by: java.net.ConnectException: connection timed out: api.steampowered.com/95.100.74.248:443
	at org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:179)
	... 23 more
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: api.steampowered.com/95.100.74.248:443
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261)
	... 12 more

**Comment by ribasco** [comment]
I'm unable to reproduce the error. Works fine in my end.  

`Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: api.steampowered.com/95.100.74.248:443`

this error indicates that it is unable to connect to the steam api url. Can you manually verify if you can access the url below from your browser (Replace `<your steam id>` and `<steam api key>`) with your values.

`https://api.steampowered.com/ISteamUser/GetPlayerBans/v1?steamids=<your steam id>&key=<steam api key>`

**Comment by MuLanMax** [comment]
> I'm unable to reproduce the error. Works fine in my end.
> 
> `Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: api.steampowered.com/95.100.74.248:443`
> 
> this error indicates that it is unable to connect to the steam api url. Can you manually verify if you can access the url below from your browser (Replace `<your steam id>` and `<steam api key>`) with your values.
> 
> `https://api.steampowered.com/ISteamUser/GetPlayerBans/v1?steamids=<your steam id>&key=<steam api key>`

Response results obtained by using postMan
<img width="807" alt="image" src="https://user-images.githubusercontent.com/67360365/206831314-d9fd25f5-c1fb-473c-90db-909485c48401.png">

**Comment by MuLanMax** [comment]
> I'm unable to reproduce the error. Works fine in my end.
> 
> `Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: api.steampowered.com/95.100.74.248:443`
> 
> this error indicates that it is unable to connect to the steam api url. Can you manually verify if you can access the url below from your browser (Replace `<your steam id>` and `<steam api key>`) with your values.
> 
> `https://api.steampowered.com/ISteamUser/GetPlayerBans/v1?steamids=<your steam id>&key=<steam api key>`

is ok
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/67360365/206831456-5743efb4-dd9f-497d-a6a7-679ce402c941.png">

**Comment by ribasco** [comment]
It is possible that your firewall is blocking inbound/outbound connections of your application, can you confirm?

**Comment by ribasco** [comment]
Closing. No further feedback. Feel free to re-open if issue still persists.
