### ISSUE TITLE
[Steam Storefront API] java.lang.ClassCastException: java.lang.String cannot be cast to com.google.gson.JsonElement on any Steam Storefront calls

### ISSUE THREAD

**Issue by mikeporterdev** [ribasco/async-gamequery-lib#26]
Tested with the following
```
SteamStorefront steamStorefront = new SteamStorefront(client);
CompletableFuture<StoreFeaturedApps> featuredApps = steamStorefront.getFeaturedApps();
StoreFeaturedApps storeFeaturedApps = featuredApps.get();
```

Causes 
```
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to com.google.gson.JsonElement
	at com.ibasco.agql.core.AbstractWebApiInterface.postProcessConversion(AbstractWebApiInterface.java:191)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at org.asynchttpclient.netty.NettyResponseFuture.getContent(NettyResponseFuture.java:219)
	at org.asynchttpclient.netty.NettyResponseFuture.done(NettyResponseFuture.java:254)
	at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.finishUpdate(AsyncHttpClientHandler.java:241)
	at org.asynchttpclient.netty.handler.HttpHandler.handleChunk(HttpHandler.java:120)
```

Drilling down into it with a debugger it looks like this might be due to the 302 Moved Temporarily of the Http call to the Steam store being moved to Https. I think changing http to https in SteamApiConstants.java line 90 should fix this

**Comment by ribasco** [comment]
Thanks for the contribution. Merging fix to main branch
