### ISSUE TITLE
Resource was not found

### ISSUE THREAD

**Issue by ribasco** [ribasco/async-gamequery-lib#29]
**Errors encountered during test:**

```java
Exception in thread "main" java.util.concurrent.ExecutionException: com.ibasco.agql.core.exceptions.ResourceNotFoundException: Resource was not found.
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at com.ibasco.agql.examples.Dota2WebApiQueryEx.run(Dota2WebApiQueryEx.java:70)
	at com.ibasco.agql.examples.Dota2WebApiQueryEx.main(Dota2WebApiQueryEx.java:48)
Caused by: com.ibasco.agql.core.exceptions.ResourceNotFoundException: Resource was not found.
	at com.ibasco.agql.core.AbstractWebApiInterface.interceptResponse(AbstractWebApiInterface.java:172)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at org.asynchttpclient.netty.NettyResponseFuture.loadContent(NettyResponseFuture.java:223)
	at org.asynchttpclient.netty.NettyResponseFuture.done(NettyResponseFuture.java:258)
	...
```

**Affected interfaces:**

- Dota2Econ.getItemIconPath()
- Dota2Fantasy.getProPlayerList()
- Dota2Match.getLeagueListing()
- Dota2Teams.getTeamInfo()

Seems like they are no longer available for *_570 interfaces. 

Reference: [steam webapi documentation (xpaw)](https://lab.xpaw.me/steam_api_documentation.html)

Should be removed from the next major release

**Comment by petersamokhin** [comment]
And what can we do? :)
Where does OpenDota get this data from?
