### ISSUE TITLE
hi  I use the ROCN library to link the game server and always prompt the link timeout

### ISSUE THREAD

**Issue by MuLanMax** [ribasco/async-gamequery-lib#86]
The name of the game is: rust

com.ibasco.agql.core.exceptions.ReadTimeoutException: null
	at com.ibasco.agql.core.exceptions.ReadTimeoutException.<clinit>(ReadTimeoutException.java:27)
	at com.ibasco.agql.core.transport.handlers.ReadTimeoutHandler.readTimedOut(ReadTimeoutHandler.java:78)
	at com.ibasco.agql.core.transport.handlers.ReadTimeoutHandler.channelIdle(ReadTimeoutHandler.java:63)
	at io.netty.handler.timeout.IdleStateHandler$ReaderIdleTimeoutTask.run(IdleStateHandler.java:504)
	at io.netty.handler.timeout.IdleStateHandler$AbstractIdleTask.run(IdleStateHandler.java:476)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)
23:15:52.344 [agql-el-1-3] DEBUG com.ibasco.agql.core.NettyMessenger - [296b3af1 : OKWIIYM4Z0K] MESSENGER => Received response for request 'Msg: [REQ:OKWIIYM4Z0K], Type: SourceRconAuthRequest, From: /192.168.50.34:61462, To: /87.*。*。*:28016' (Error: ReadTimeoutException)
23:15:52.344 [agql-el-1-3] DEBUG com.ibasco.agql.core.NettyMessenger - [296b3af1 : OKWIIYM4Z0K] MESSENGER => [ERROR] Received response in error (Request: 'Msg: [REQ:OKWIIYM4Z0K], Type: SourceRconAuthRequest, From: /192.168.50.34:61462, To: /87.*。*。*  28016', Error: ReadTimeoutException)
com.ibasco.agql.core.exceptions.ReadTimeoutException: null
	at com.ibasco.agql.core.exceptions.ReadTimeoutException.<clinit>(ReadTimeoutException.java:27)
	at com.ibasco.agql.core.transport.handlers.ReadTimeoutHandler.readTimedOut(ReadTimeoutHandler.java:78)
	at com.ibasco.agql.core.transport.handlers.ReadTimeoutHandler.channelIdle(ReadTimeoutHandler.java:63)
	at io.netty.handler.timeout.IdleStateHandler$ReaderIdleTimeoutTask.run(IdleStateHandler.java:504)
	at io.netty.handler.timeout.IdleStateHandler$AbstractIdleTask.run(IdleStateHandler.java:476)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)
23:15:52.347 [agql-el-1-3] DEBUG com.ibasco.agql.core.transport.pool.DefaultChannelPoolHandler - [296b3af1 : OKWIIYM4Z0K] HANDLER => Channel Released (Active: true, Open: true, Registered: true)
23:15:52.348 [agql-el-1-3] DEBUG com.ibasco.agql.core.transport.pool.DefaultChannelPoolHandler - [296b3af1 : OKWIIYM4Z0K] HANDLER => Removed READ/WRITE Timeout Handlers
23:15:52.348 [agql-el-1-3] DEBUG com.ibasco.agql.core.NettyChannelContext - [296b3af1 : OKWIIYM4Z0K] CONTEXT (RELEASE) => Context released (Pooled)
23:15:52.348 [agql-el-1-3] DEBUG com.ibasco.agql.core.NettyChannelContext - [296b3af1 : OKWIIYM4Z0K] CONTEXT => Skipping auto release
Exception in thread "main" java.util.concurrent.CompletionException: com.ibasco.agql.protocols.valve.source.query.rcon.exceptions.RconException: com.ibasco.agql.core.exceptions.MessengerException: com.ibasco.agql.core.exceptions.ReadTimeoutException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:838)
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:811)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
	at dev.failsafe.spi.FailsafeFuture.completeResult(FailsafeFuture.java:99)
	at dev.failsafe.AsyncExecutionImpl.complete(AsyncExecutionImpl.java:159)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
	at dev.failsafe.internal.RetryPolicyExecutor.lambda$null$5(RetryPolicyExecutor.java:155)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:792)
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2153)
	at dev.failsafe.internal.RetryPolicyExecutor.lambda$handleAsync$6(RetryPolicyExecutor.java:150)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
	at dev.failsafe.spi.PolicyExecutor.lambda$null$2(PolicyExecutor.java:109)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
	at dev.failsafe.Functions.lambda$null$5(Functions.java:202)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
	at dev.failsafe.Functions.lambda$null$2(Functions.java:152)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
	at com.ibasco.agql.core.NettyChannelContext.markInError(NettyChannelContext.java:361)
	at com.ibasco.agql.core.NettyMessenger.receive(NettyMessenger.java:340)
	at com.ibasco.agql.core.NettyChannelContext.receive(NettyChannelContext.java:375)
	at com.ibasco.agql.core.transport.handlers.MessageRouter.exceptionCaught(MessageRouter.java:208)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
	at com.ibasco.agql.protocols.valve.source.query.rcon.handlers.SourceRconPacketAssembler.exceptionCaught(SourceRconPacketAssembler.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
	at com.ibasco.agql.protocols.valve.source.query.rcon.handlers.SourceRconPacketDecoder.exceptionCaught(SourceRconPacketDecoder.java:271)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
	at com.ibasco.agql.core.transport.handlers.MessageDecoder.exceptionCaught(MessageDecoder.java:93)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
	at com.ibasco.agql.core.transport.handlers.ReadTimeoutHandler.readTimedOut(ReadTimeoutHandler.java:78)
	at com.ibasco.agql.core.transport.handlers.ReadTimeoutHandler.channelIdle(ReadTimeoutHandler.java:63)
	at io.netty.handler.timeout.IdleStateHandler$ReaderIdleTimeoutTask.run(IdleStateHandler.java:504)
	at io.netty.handler.timeout.IdleStateHandler$AbstractIdleTask.run(IdleStateHandler.java:476)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)
Caused by: com.ibasco.agql.protocols.valve.source.query.rcon.exceptions.RconException: com.ibasco.agql.core.exceptions.MessengerException: com.ibasco.agql.core.exceptions.ReadTimeoutException
	at com.ibasco.agql.protocols.valve.source.query.rcon.SourceRconMessenger$RequestContext.collectAndRelease(SourceRconMessenger.java:927)
	at com.ibasco.agql.protocols.valve.source.query.rcon.SourceRconMessenger$RequestContext.access$1500(SourceRconMessenger.java:903)
	at com.ibasco.agql.protocols.valve.source.query.rcon.SourceRconMessenger.lambda$send$7(SourceRconMessenger.java:290)
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:836)
	... 68 more
Caused by: com.ibasco.agql.core.exceptions.MessengerException: com.ibasco.agql.core.exceptions.ReadTimeoutException
	at com.ibasco.agql.core.NettyMessenger.wrapException(NettyMessenger.java:285)
	at java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1119)
	at java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1084)
	... 37 more
Caused by: com.ibasco.agql.core.exceptions.ReadTimeoutException
	at com.ibasco.agql.core.exceptions.ReadTimeoutException.<clinit>(ReadTimeoutException.java:27)

**Comment by ribasco** [comment]
Have you double-checked if the IP is reachable? A timeout exception usually means the server isn't responding to the request. 

I have not yet tested this library on Rust so I'll give it a try on my end to make sure it works.

**Comment by ribasco** [comment]
Just an update, I was able to successfully connect and authenticate to my local rust instance with `rcon.web` property set to `false` (legacy). However, command requests are failing due to an exception thrown. I have opened a new issue (Issue #87) and will have to look into this further.

**Comment by ribasco** [comment]
The fix has been uploaded to the sonatype snapshots repository (`1.0.5-SNAPSHOT`). Can you test and confirm the changes? Thanks

```java
<dependency>
  <groupId>com.ibasco.agql</groupId>
  <artifactId>agql-source-rcon</artifactId>
  <version>1.0.5-SNAPSHOT</version>
</dependency>
```

**Comment by MuLanMax** [comment]
> 修复程序已上传到 sonatype 快照存储库 ( `1.0.5-SNAPSHOT`)。您可以测试并确认更改吗？谢谢
> 
> ```java
> <dependency>
>   <groupId>com.ibasco.agql</groupId>
>   <artifactId>agql-source-rcon</artifactId>
>   <version>1.0.5-SNAPSHOT</version>
> </dependency>
> ```

Unresolved dependency: 'com.ibasco.agql:agql-source-rcon:jar:1.0.5-SNAPSHOT'

**Comment by ribasco** [comment]
update your maven's `settings.xml` and add the sonatype repository. 

example:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
    <activeProfiles>
        <activeProfile>nexus</activeProfile>
    </activeProfiles>
    <profiles>
        <profile>
            <id>nexus</id>
            <repositories>
                <repository>
                    <id>sonatype-snapshots</id>
                    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
                    <layout>default</layout>
                    <releases>
                        <enabled>false</enabled>
                    </releases>
                    <snapshots>
                        <enabled>true</enabled>
                    </snapshots>
                </repository>
            </repositories>
        </profile>
    </profiles>
</settings>
```

**Comment by ribasco** [comment]
hello, any updates on this issue? have you tested the changes?

**Comment by MuLanMax** [comment]
> 你好，关于这个问题的任何更新？你测试过这些变化吗？

I'm very sorry. I've been studying websocket recently, but I haven't tested the things you modified

**Comment by ribasco** [comment]
> > 你好，关于这个问题的任何更新？你测试过这些变化吗？
> 
> I'm very sorry. I've been studying websocket recently, but I haven't tested the things you modified

No problem! I will go ahead and publish the changes. In case you decide to use this library and find any more issues related to this matter, feel free to open a new issue. Thank you!
