### ISSUE TITLE
Rust RCON: Invalid packet type: 4

### ISSUE THREAD

**Issue by ribasco** [ribasco/async-gamequery-lib#87]
Related to issue #86 

RCON commands to a rust server fails due to an exception thrown.

The server sends a packet type of '4' which is not officially documented in the source rcon protocol documentation. 

```java
com.ibasco.agql.protocols.valve.source.query.rcon.exceptions.RconException: io.netty.handler.codec.DecoderException: com.ibasco.agql.core.exceptions.PacketDecodeException: Invalid packet type: 4
	at com.ibasco.agql.protocols.valve.source.query.rcon.SourceRconMessenger$RequestContext.collectAndRelease(SourceRconMessenger.java:927)
	at com.ibasco.agql.protocols.valve.source.query.rcon.SourceRconMessenger$RequestContext.access$1500(SourceRconMessenger.java:903)
	at com.ibasco.agql.protocols.valve.source.query.rcon.SourceRconMessenger.lambda$send$7(SourceRconMessenger.java:290)
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:836)
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:811)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
	at dev.failsafe.spi.FailsafeFuture.completeResult(FailsafeFuture.java:99)
	at dev.failsafe.AsyncExecutionImpl.complete(AsyncExecutionImpl.java:159)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
	at dev.failsafe.internal.RetryPolicyExecutor.lambda$null$5(RetryPolicyExecutor.java:155)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:792)
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2153)
	at dev.failsafe.internal.RetryPolicyExecutor.lambda$handleAsync$6(RetryPolicyExecutor.java:150)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
	at dev.failsafe.spi.PolicyExecutor.lambda$null$2(PolicyExecutor.java:109)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
	at dev.failsafe.Functions.lambda$null$5(Functions.java:202)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
	at dev.failsafe.Functions.lambda$null$2(Functions.java:152)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
	at com.ibasco.agql.core.NettyChannelContext.markInError(NettyChannelContext.java:361)
	at com.ibasco.agql.core.NettyMessenger.receive(NettyMessenger.java:340)
	at com.ibasco.agql.core.NettyChannelContext.receive(NettyChannelContext.java:375)
	at com.ibasco.agql.core.transport.handlers.MessageRouter.exceptionCaught(MessageRouter.java:208)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
	at com.ibasco.agql.protocols.valve.source.query.rcon.handlers.SourceRconPacketAssembler.exceptionCaught(SourceRconPacketAssembler.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
	at com.ibasco.agql.protocols.valve.source.query.rcon.handlers.SourceRconPacketDecoder.exceptionCaught(SourceRconPacketDecoder.java:271)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:381)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at com.ibasco.agql.core.transport.handlers.MessageDecoder.channelRead(MessageDecoder.java:75)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)
Caused by: io.netty.handler.codec.DecoderException: com.ibasco.agql.core.exceptions.PacketDecodeException: Invalid packet type: 4
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:480)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
	at com.ibasco.agql.protocols.valve.source.query.rcon.handlers.SourceRconPacketDecoder.channelRead(SourceRconPacketDecoder.java:95)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	... 25 more
Caused by: com.ibasco.agql.core.exceptions.PacketDecodeException: Invalid packet type: 4
	at com.ibasco.agql.protocols.valve.source.query.rcon.packets.SourceRconPacketDecoder.decode(SourceRconPacketDecoder.java:103)
	at com.ibasco.agql.protocols.valve.source.query.rcon.packets.SourceRconPacketDecoder.decode(SourceRconPacketDecoder.java:38)
	at com.ibasco.agql.protocols.valve.source.query.rcon.handlers.SourceRconPacketDecoder.decode(SourceRconPacketDecoder.java:198)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
	... 28 more
```

**Comment by ribasco** [comment]
This is the packet dump of the decoded response (packet type 4) after issuing a `status` command

```
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 5b 52 43 4f 4e 5d 5b 31 39 32 2e 31 36 38 2e 35 |[RCON][192.168.5|
|00000010| 30 2e 33 3a 36 31 34 35 34 5d 20 73 74 61 74 75 |0.3:61454] statu|
|00000020| 73 00                                           |s.              |
+--------+-------------------------------------------------+----------------+
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 68 6f 73 74 6e 61 6d 65 3a 20 52 75 73 74 0a 76 |hostname: Rust.v|
|00000010| 65 72 73 69 6f 6e 20 3a 20 32 33 34 35 20 73 65 |ersion : 2345 se|
|00000020| 63 75 72 65 20 28 73 65 63 75 72 65 20 6d 6f 64 |cure (secure mod|
|00000030| 65 20 65 6e 61 62 6c 65 64 2c 20 63 6f 6e 6e 65 |e enabled, conne|
|00000040| 63 74 65 64 20 74 6f 20 53 74 65 61 6d 33 29 0a |cted to Steam3).|
|00000050| 6d 61 70 20 20 20 20 20 3a 20 50 72 6f 63 65 64 |map     : Proced|
|00000060| 75 72 61 6c 20 4d 61 70 0a 70 6c 61 79 65 72 73 |ural Map.players|
|00000070| 20 3a 20 30 20 28 35 30 20 6d 61 78 29 20 28 30 | : 0 (50 max) (0|
|00000080| 20 71 75 65 75 65 64 29 20 28 30 20 6a 6f 69 6e | queued) (0 join|
|00000090| 69 6e 67 29 0a 0a 69 64 20 6e 61 6d 65 20 70 69 |ing)..id name pi|
|000000a0| 6e 67 20 63 6f 6e 6e 65 63 74 65 64 20 61 64 64 |ng connected add|
|000000b0| 72 20 6f 77 6e 65 72 20 76 69 6f 6c 61 74 69 6f |r owner violatio|
|000000c0| 6e 20 6b 69 63 6b 73 20 0a 00                   |n kicks ..      |
+--------+-------------------------------------------------+----------------+
```

**Observations:**

- The server initially responds with a packet of type 4 (undocumented) which looks like a feedback regarding the issued command.
- Then immediately followed by a another packet of type 0 (documented) which contains the actual response of the server

**Comment by ribasco** [comment]
Rust has transitioned from legacy to web rcon (using web sockets) which is not officially supported by this library. There is a note on their [readme ](https://github.com/Facepunch/webrcon#rust) stating that the legacy will be removed sometime in the future so its worth adding a note in the project documentation.

As to whether or not I will support this new mode in the library, I'll put it in consideration if there is demand for it.

**Comment by MuLanMax** [comment]
Hello, I now want to develop a set of web management pages based on your code base, tools like rustadmin. I'm very sorry, my English is not very good, and I don't understand some meaning

**Comment by ribasco** [comment]
> Hello, I now want to develop a set of web management pages based on your code base, tools like rustadmin. 

I will see if I can make some changes in this library to make rcon work with Rust. 

But please keep in mind that this library only supports the [Source Rcon Protocol](https://developer.valvesoftware.com/wiki/Source_RCON_Protocol). Facepunch decided to switch from `Source Rcon` to [Webrcon ](https://github.com/Facepunch/webrcon) (using Web sockets) some time ago. 

If you are planning to develop new management based apps using RCON, you might want to consider using a another library that supports rust's websockets version since the legacy mode might be removed in the future.
