### ISSUE TITLE
Incompatibility with Spring Boot

### ISSUE THREAD

**Issue by DarkAtra** [ribasco/async-gamequery-lib#94]
It seems like this lib is not working as expected when repackaging everything into a fat jar using the `spring-boot-maven-plugin`. For some reason it complains that the `failsafeEnabled` Option does not exist:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: java.lang.IllegalStateException: Option key 'failsafeEnabled' does not exists
        at com.ibasco.agql.core.util.Options.getOrDefault(Options.java:117)
        at com.ibasco.agql.core.util.Options.getOrDefault(Options.java:111)
        at com.ibasco.agql.core.util.FailsafeBuilder.buildRetryPolicy(FailsafeBuilder.java:91)
        at com.ibasco.agql.core.transport.FailsafeChannelFactory.buildRetryPolicy(FailsafeChannelFactory.java:97)
        at com.ibasco.agql.core.transport.FailsafeChannelFactory.<init>(FailsafeChannelFactory.java:79)
        at com.ibasco.agql.core.transport.DefaultNettyChannelFactoryProvider.getContextualFactory(DefaultNettyChannelFactoryProvider.java:68)
        at com.ibasco.agql.protocols.valve.source.query.SourceQueryMessenger.createChannelFactory(SourceQueryMessenger.java:223)
        at com.ibasco.agql.core.NettyMessenger.<init>(NettyMessenger.java:84)
```

This could also be a bug in Spring, but I wanted to check with you first since you may know further details.

Here's the project that reproduces the issue: https://github.com/DarkAtra/server-query-issue

**Comment by ribasco** [comment]
Appreciate the reproducer! Saved me some time. 

This looks like an issue with the library failing to find and dynamically load the `Option` classes at runtime when running from a JAR. I'll have to look into this further and see if I can come up with a much simpler approach.

**Comment by ribasco** [comment]
The fix is now available at [1.0.6-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/com/ibasco/agql/agql-source-query/1.0.6-SNAPSHOT/). I will publish once I get a confirmation that everything is working from your end.

**Comment by DarkAtra** [comment]
While the fix seems to work, the client became very noisy:

```
2022-07-12 12:33:19.823  WARN 3836 --- [tcher-worker-21] com.ibasco.agql.core.util.Option         : initialize(): Skipped cache entry 'CacheEntry{context=class com.ibasco.agql.core.util.ConnectOptions, option=Option{id=AZB1GQSI3VU, key='failsafeEnabled', defaultValue=true, fieldName='FAILSAFE_ENABLED'}}' for parent class 'class com.ibasco.agql.protocols.valve.source.query.SourceQueryOptions'
2022-07-12 12:33:19.823  WARN 3836 --- [tcher-worker-21] com.ibasco.agql.core.util.Option         : initialize(): Skipped cache entry 'CacheEntry{context=class com.ibasco.agql.core.util.ConnectOptions, option=Option{id=DHCS1N30SUO, key='failsafeRateLimitEnabled', defaultValue=true, fieldName='FAILSAFE_RATELIMIT_ENABLED'}}' for parent class 'class com.ibasco.agql.protocols.valve.source.query.SourceQueryOptions'
2022-07-12 12:33:19.823  WARN 3836 --- [tcher-worker-21] com.ibasco.agql.core.util.Option         : initialize(): Skipped cache entry 'CacheEntry{context=class com.ibasco.agql.core.util.ConnectOptions, option=Option{id=DKKDXPOSBF4, key='failsafeRateLimitMaxExec', defaultValue=650, fieldName='FAILSAFE_RATELIMIT_MAX_EXEC'}}' for parent class 'class com.ibasco.agql.protocols.valve.source.query.SourceQueryOptions'
2022-07-12 12:33:19.823  WARN 3836 --- [tcher-worker-21] com.ibasco.agql.core.util.Option         : initialize(): Skipped cache entry 'CacheEntry{context=class com.ibasco.agql.core.util.ConnectOptions, option=Option{id=1WKQ9IUJRSK, key='failsafeRateLimitPeriod', defaultValue=5000, fieldName='FAILSAFE_RATELIMIT_PERIOD'}}' for parent class 'class com.ibasco.agql.protocols.valve.source.query.SourceQueryOptions'
2022-07-12 12:33:19.823  WARN 3836 --- [tcher-worker-21] com.ibasco.agql.core.util.Option         : initialize(): Skipped cache entry 'CacheEntry{context=class com.ibasco.agql.core.util.ConnectOptions, option=Option{id=CXUGJVWU7DC, key='failsafeRateLimitMaxWaitTime', defaultValue=10000, fieldName='FAILSAFE_RATELIMIT_MAX_WAIT_TIME'}}' for parent class 'class com.ibasco.agql.protocols.valve.source.query.SourceQueryOptions'
2022-07-12 12:33:19.823  WARN 3836 --- [tcher-worker-21] com.ibasco.agql.core.util.Option         : initialize(): Skipped cache entry 'CacheEntry{context=class com.ibasco.agql.core.util.ConnectOptions, option=Option{id=CFA8RCTRV0, key='failsafeRateLimitType', defaultValue=SMOOTH, fieldName='FAILSAFE_RATELIMIT_TYPE'}}' for parent class 'class com.ibasco.agql.protocols.valve.source.query.SourceQueryOptions'
2022-07-12 12:33:19.823  WARN 3836 --- [tcher-worker-21] com.ibasco.agql.core.util.Option         : initialize(): Skipped cache entry 'CacheEntry{context=class com.ibasco.agql.core.util.ConnectOptions, option=Option{id=PQ7RIFNPVBA, key='failsafeRetryRetryEnabled', defaultValue=true, fieldName='FAILSAFE_RETRY_ENABLED'}}' for parent class 'class com.ibasco.agql.protocols.valve.source.query.SourceQueryOptions'
2022-07-12 12:33:19.823  WARN 3836 --- [tcher-worker-21] com.ibasco.agql.core.util.Option         : initialize(): Skipped cache entry 'CacheEntry{context=class com.ibasco.agql.core.util.ConnectOptions, option=Option{id=R64TQ6ODSKS, key='failsafeRetryDelay', defaultValue=1000, fieldName='FAILSAFE_RETRY_DELAY'}}' for parent class 'class com.ibasco.agql.protocols.valve.source.query.SourceQueryOptions'
2022-07-12 12:33:19.823  WARN 3836 --- [tcher-worker-21] com.ibasco.agql.core.util.Option         : initialize(): Skipped cache entry 'CacheEntry{context=class com.ibasco.agql.core.util.ConnectOptions, option=Option{id=0L35ZLFY4, key='failsafeRetryBackoffEnabled', defaultValue=true, fieldName='FAILSAFE_RETRY_BACKOFF_ENABLED'}}' for parent class 'class com.ibasco.agql.protocols.valve.source.query.SourceQueryOptions'
2022-07-12 12:33:19.823  WARN 3836 --- [tcher-worker-21] com.ibasco.agql.core.util.Option         : initialize(): Skipped cache entry 'CacheEntry{context=class com.ibasco.agql.core.util.ConnectOptions, option=Option{id=HQHC67BYF3Q, key='failsafeRetryBackoffDelay', defaultValue=50, fieldName='FAILSAFE_RETRY_BACKOFF_DELAY'}}' for parent class 'class com.ibasco.agql.protocols.valve.source.query.SourceQueryOptions'
2022-07-12 12:33:19.823  WARN 3836 --- [tcher-worker-21] com.ibasco.agql.core.util.Option         : initialize(): Skipped cache entry 'CacheEntry{context=class com.ibasco.agql.core.util.ConnectOptions, option=Option{id=H5UKIHNEIE, key='failsafeRetryBackoffMaxDelay', defaultValue=5000, fieldName='FAILSAFE_RETRY_BACKOFF_MAX_DELAY'}}' for parent class 'class com.ibasco.agql.protocols.valve.source.query.SourceQueryOptions'
2022-07-12 12:33:19.823  WARN 3836 --- [tcher-worker-21] com.ibasco.agql.core.util.Option         : initialize(): Skipped cache entry 'CacheEntry{context=class com.ibasco.agql.core.util.ConnectOptions, option=Option{id=O7LV3K7NC0, key='failsafeRetryBackoffDelayFactor', defaultValue=1.5, fieldName='FAILSAFE_RETRY_BACKOFF_DELAY_FACTOR'}}' for parent class 'class com.ibasco.agql.protocols.valve.source.query.SourceQueryOptions'
2022-07-12 12:33:19.823  WARN 3836 --- [tcher-worker-21] com.ibasco.agql.core.util.Option         : initialize(): Skipped cache entry 'CacheEntry{context=class com.ibasco.agql.core.util.ConnectOptions, option=Option{id=ILJ5UKOKBVY, key='failsafeRetryMaxAttempts', defaultValue=3, fieldName='FAILSAFE_RETRY_MAX_ATTEMPTS'}}' for parent class 'class com.ibasco.agql.protocols.valve.source.query.SourceQueryOptions'
2022-07-12 12:33:19.823  WARN 3836 --- [tcher-worker-21] com.ibasco.agql.core.util.Option         : initialize(): Skipped cache entry 'CacheEntry{context=class com.ibasco.agql.core.util.ConnectOptions, option=Option{id=GW86CSTXRVE, key='failsafeCircuitBreakerEnabled', defaultValue=true, fieldName='FAILSAFE_CIRCBREAKER_ENABLED'}}' for parent class 'class com.ibasco.agql.protocols.valve.source.query.SourceQueryOptions'
2022-07-12 12:33:19.823  WARN 3836 --- [tcher-worker-21] com.ibasco.agql.core.util.Option         : initialize(): Skipped cache entry 'CacheEntry{context=class com.ibasco.agql.core.util.ConnectOptions, option=Option{id=MJLAF65DGC, key='failsafeCircuitBreakerDelay', defaultValue=1000, fieldName='FAILSAFE_CIRCBREAKER_DELAY'}}' for parent class 'class com.ibasco.agql.protocols.valve.source.query.SourceQueryOptions'
2022-07-12 12:33:19.823  WARN 3836 --- [tcher-worker-21] com.ibasco.agql.core.util.Option         : initialize(): Skipped cache entry 'CacheEntry{context=class com.ibasco.agql.core.util.ConnectOptions, option=Option{id=PGIFRGAZEEY, key='failsafeCircuitBreakerFailureThreshold', defaultValue=3, fieldName='FAILSAFE_CIRCBREAKER_FAILURE_THRESHOLD'}}' for parent class 'class com.ibasco.agql.protocols.valve.source.query.SourceQueryOptions'
2022-07-12 12:33:19.823  WARN 3836 --- [tcher-worker-21] com.ibasco.agql.core.util.Option         : initialize(): Skipped cache entry 'CacheEntry{context=class com.ibasco.agql.core.util.ConnectOptions, option=Option{id=TLHWXF6D2W, key='failsafeCircuitBreakerFailureThresholdingCapacity', defaultValue=5, fieldName='FAILSAFE_CIRCBREAKER_FAILURE_THRESHOLDING_CAP'}}' for parent class 'class com.ibasco.agql.protocols.valve.source.query.SourceQueryOptions'
2022-07-12 12:33:19.823  WARN 3836 --- [tcher-worker-21] com.ibasco.agql.core.util.Option         : initialize(): Skipped cache entry 'CacheEntry{context=class com.ibasco.agql.core.util.ConnectOptions, option=Option{id=PMRNM9DIXYG, key='failsafeCircuitBreakerSuccessThreshold', defaultValue=1, fieldName='FAILSAFE_CIRCBREAKER_SUCCESS_THRESHOLD'}}' for parent class 'class com.ibasco.agql.protocols.valve.source.query.SourceQueryOptions'
```

Is this intended?

**Comment by ribasco** [comment]
> Hey, thanks for fixing the issue, it works as expected. However, I just noticed that the client became kinda noisy:
> 
> There are a lot of info logs as well. Is this intended?

You're right, those are no longer needed. I will remove them, thanks!

**Comment by DarkAtra** [comment]
I just updated to the latest version, works as expected. Ty again, feel free to close the issue ^^
